#!/usr/bin/env bash
docker kill theprimeagen
git pull origin master
docker rm theprimeagen
docker build . -t theprimeagen
# docker run --env QUIRK_TOKEN --name theprimeagen -d --restart always -p 1337:1337 theprimeagen
docker run --name theprimeagen -d --restart always -p 80:1337 theprimeagen

